name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # O el que uses localmente

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Ejecutar pruebas
        run: python -m pytest -s tests/ --junitxml=results.xml

      - name: Subir resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultados-pruebas
          path: results.xml
